export const US_CITIES = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Miami",
  "Orlando",
  "Tampa",
  "Jacksonville",
  "Fort Lauderdale",
  "Atlanta",
  "Savannah",
  "Charlotte",
  "Raleigh",
  "Durham",
  "Washington",
  "Seattle",
  "Tacoma",
  "Portland",
  "San Francisco",
  "Oakland",
  "Berkeley",
  "San Mateo",
  "Palo Alto",
  "Mountain View",
  "San Bruno",
  "Sunnyvale",
  "Santa Clara",
  "Cupertino",
  "San Bernardino",
  "Riverside",
  "Irvine",
  "Anaheim",
  "Pasadena",
  "Burbank",
  "Glendale",
  "Santa Monica",
  "Beverly Hills",
  "West Hollywood",
  "Inglewood",
  "Compton",
  "Long Beach",
  "Santa Ana",
  "Huntington Beach",
  "Fresno",
  "Bakersfield",
  "Stockton",
  "Sacramento",
  "San Rafael",
  "Santa Rosa",
  "Napa",
  "Sonoma",
  "Santa Cruz",
  "Monterey",
  "Salinas",
  "Modesto",
  "Visalia",
  "Redding",
  "Chico",
  "Eureka"
];
